server:
  port: 3344

spring:
  application:
    name:  wallet-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:wyb01/microservicecloud-config.git #GitHub上面的git仓库名字