server:
  port: 9527

spring:
  application:
    name: wallet-zuul-gateway  #注入进eureka微服务名称

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


zuul:
  #ignored-services: wallet-provider  #单个 （原真实服务名忽略）
  prefix: /wallet                     #设置统一公共前缀
  ignored-services: "*"               #多个

  routes:                               #域名映射
    mydept.serviceId: wallet-provider   #微服务真实地址
    mydept.path: /mydept/**             #配置后对外提供的虚拟地址

info:
  app.name: wallet-zuul-gateway
  build.artifactId: $project.artifactId$
  build.version: $project.version$



